# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-15 10:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments')),
            ],
            options={
                'db_table': 'Attachment',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Administrator')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_evidence', models.CharField(blank=True, max_length=500, null=True, verbose_name='additional evidence')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='webapp.Department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='webapp.Location')),
            ],
            options={
                'ordering': ['-report_date'],
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('reporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_no', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number!', message='Phone number must be in the format xxxx-xxxxxxx', regex='^03\\d{2}\\W\\d{7}$')])),
                ('user_reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reporter',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('report_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=20, verbose_name='crime/illegal activity')),
            ],
            options={
                'db_table': 'Report Type',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='webapp.ReportType'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Reporter'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Report'),
        ),
    ]
